export const AUTH_PAGE_REQUEST = "AUTH_PAGE_REQUEST"
export const AUTH_PAGE_SUCCESS = "AUTH_PAGE_SUCCESS"
export const AUTH_PAGE_ERROR = "AUTH_PAGE_ERROR"

export const AUTH_CLEAR_DATA = "AUTH_CLEAR_DATA"