export const LISTMOVIE_REQUEST = "LISTMOVIE_REQUEST"
export const LISTMOVIE_SUCCESS = "LISTMOVIE_SUCCESS"
export const LISTMOVIE_ERROR = "LISTMOVIE_ERROR"

export const SEARCH_MOVIE = "SEARCH_MOVIE"
export const DELETE_MOVIE = "DELETE_MOVIE"