export const LISTMOVIE_PHANTRANG_REQUEST = "LISTMOVIE_PHANTRANG_REQUEST"
export const LISTMOVIE_PHANTRANG_SUCCESS = "LISTMOVIE_PHANTRANG_SUCCESS"
export const LISTMOVIE_PHANTRANG_ERROR = " LISTMOVIE_PHANTRANG_ERROR"