export const MANAGER_REQUEST = "MANAGER_REQUEST";
export const MANAGER_SUCCESS = "MANAGER_SUCCESS";
export const MANAGER_FAILED = "MANAGER_FAILED";
export const SEARCH_USER = "SEARCH_USER";
export const DELETE_USER = "DELETE_USER";