export const ADDFILM_REQUEST = "ADDFILM_REQUEST"
export const ADDFILM_SUCCESS = "ADDFILM_SUCCESS"
export const ADDFILM_ERROR = "ADDFILM_ERROR"

export const LAYTHONGTINFILM_SUCCESS = 'LAYTHONGTINFILM_SUCCESS'